package main

import "fmt"

var DNA = "AGCGGGATTCATTTCATAACACGAAGGCTTATCTAAACGAGAGCGGTCCGGCTAAAGTTTGACAACCCGCATGGGGTAAGGTGTACGTAGGTCATATCCTAAATAAACTCATCTAGTCTGAAGACGTGTACCAGTGAAGTGGACGCAATACCCCAGTGATGGAATCAAACTTGTAGCTGCGCTGAGTATTTAGGCGCCGAAAATGCATGATACTTTGTAGCAGAAAAGGCAAAGAATAAAGATTTCTCTCCCGTCCGAGGAGGTTAAATATATATGTTGAGGGGATGATTGAAATTCAAAGATCTATCCCTAACACCAGTGTTCGACACTCACGATTCGCCCAGCTTGAAGCAAAACCGCGACCACGTTGGCCCATACACGAGTTCAGACAGCAGGACGCGGTGGTCTACCCAGCACAGCGTATCCCGTTGGAAGCACAAGATCCTCTGCTCTGTCTGGAGTCTTGTGGACCCAAAGAAGGTATACTGACTCTAAGCAGTCGTGTGGTAGTCTACTGGTATGATATTTGTAGAGTCGGAACTTTGATCTCTTTCTGCTCTTTGTAGTCGATTTCACCCGGACCGCTTTGGGAACTACCTCGGTGAGGAGTTGACGTGGCCCGACGCGCACTCACGCTTGTTGTTGGCATTGTGCTCTCAATTCTGTTTCAGTCCTGGTGCCGCTGCCGTTACTAACTAGATCCTGGATACCGCTAATCCCGACATCAACTTCGTGGACTTTTTTAATAACCACAGGTCGCGAATTGCGTACGCTCCATGCGGGCACCATATAGCCGACGCGGGAGGTTCTGAGTCTGGCTGTCAAT"
var DNARNA = "GCCTTTAGACGGGGCAGTCCATGGAGAGAACCTCATGCTGTGCAGGAAGCGAAAAGCGAGTGACTGGCCGTAGTGCGTAAACGCGGGCAATAGCAGCCCGCCCCCCCTGGGAATTTCACTGTTATATCAACAGGCAATCCATTAACGCCTGCTCCTTGATGTCATCAAACCTCCTGATAACTGAGCCGGCAGAAGTAGTTAGTTTACGACAAAGGAGGGACGCGGAATCACGCGGCAGTATGGTGGAACATCCCGCCAATCTTGTTCACGGTAGATGTCCTAAGTTCAAGTCGCGCGGCTCGCCCGACCTTTCGTGTGGTCGGGGTGCAAATACCACCGTAGTAATTCAAGTCGGTTGCGATCCGGCTCTCGCCACGTTAACACCCGAGGTCGTCACGGGTGCTCGGCCGCACAACACTAAACGGTACCGATAATGTGACAAATGGTATAAAATCGGTGGATTTCCTAAGGCCAAGTAAGTGCCGACTTTGTACGGGTTAATTCGGCGATAATTATTTTCTAAAATGACGAACGAAGCCAGAGCCACTAATCTATTCGCGGTCAAATAAATGAGTAATTCTGTAGCGGTGTAGCTTGGTTGCTGTGCACCGAATCGTATTAGCTTAAGCCCAGTATGACATTCCAGGCAGGAATGTTAGGGATGAGGATTCGACTTGACGCGCCCAGCCTCTCTTTGGGATGGATATGTCACACATAGGGATCGTTTCGATGTGAAACAGTAAGTCCGAGGAAATTTCGGAGCGATGAGGGCTTGATAGTCGATTTCGATATCGCATTAGTGTTTAATGGTGCGTTGTTTATATCGCAACTTGACGGGAACTTAGCCCGCATCGTGTCCATAACCATCCGGTGATCGTGCCACACGACGCCTACTCTCGTAGGCTGGCAGTTAAATGGCGTCTGTTTC"

func countDNABases(strand string) map[string]int {
	var baseMaps = map[string]int{
		"A": 0,
		"C": 0,
		"G": 0,
		"T": 0,
	}
	for _, base := range strand {
		switch string(base) {
		case "A":
			baseMaps["A"] += 1
		case "C":
			baseMaps["C"] += 1
		case "G":
			baseMaps["G"] += 1
		case "T":
			baseMaps["T"] += 1
		}
	}
	//	fmt.Print(baseMaps)
	return baseMaps
}

func transDNAToRNA(strand string) string {
	outString := ""
	for _, base := range strand {
		switch string(base) {
		case "T":
			outString = outString + "U"
		default:
			outString = outString + string(base)
		}
	}
	return outString
}

func main() {
	//Count DNA Bases
	for _, v := range countDNABases(DNA) {
		fmt.Printf("%d ", v)
	}
	fmt.Println()

	//Transcribe DNA to RNA
	fmt.Println(transDNAToRNA(DNARNA))
	fmt.Println()
}
